軽微な修正
インデントを修正

diff --git a/bin/bm_search b/bin/bm_search
--- a/bin/bm_search
+++ b/bin/bm_search
@@ -29,9 +29,9 @@ while [ "${#}" -gt 0 ]; do
 
 		# 国立国会図書館
         -n)
-            api="ndl"
-            shift
-            ;;
+			api="ndl"
+			shift
+			;;
 
 		# フォールバック
 		-f)
@@ -41,12 +41,12 @@ while [ "${#}" -gt 0 ]; do
 
 		# 未知のオプション
         -*)
-            echo "Unknown option: $1" 1>&2
-            exit 1
-            ;;
+			echo "Error: Unknown option: $1" 1>&2
+			exit 1
+			;;
 
 		# ISBN引数
-        [0-9]*)
+		[0-9]*)
             if [ -z "${isbn_arg}" ]; then
 
                 isbn_arg="${1}"
