軽微な修正
エラーメッセージの修正
grepの不要な引数の削除
awkでの分岐の処理条件を修正

diff --git a/bin/book_manager b/bin/book_manager
--- a/bin/book_manager
+++ b/bin/book_manager
@@ -29,7 +29,7 @@ set -ue
 
 
 # apiを叩き,結果を加工
-hit_api(){
+parser(){
 
 	# wgetがシステム内に存在するかを確認
 	if type wget > /dev/null 2>&1 ; then
@@ -46,38 +46,39 @@ hit_api(){
 	else
 
 		# wgetもcurlもない場合はメッセージを表示
-		echo 'please install "wget" or "curl"' 1>&2
+		echo 'Error: please install "wget" or "curl"' 1>&2
 
 	fi |
 
 	# isbn,タイトル,出版社,発売日,著者を抽出
-	grep -F -w -e "isbn" -e "title" -e "publisher" -e "pubdate" -e "author" |
+	grep -F -e "isbn" -e "title" -e "publisher" -e "pubdate" -e "author" |
 
 	# 区切り文字をダブルクォートに指定
-	awk -F "\"" '{
+	awk -F "\"" '
 
-		# 行頭が"      "author""にマッチする場合は真
-		if(/^      "author"/) {
+	{
 
-			# 真の場合の処理
+		# 2フィールド目が"author""にマッチすれば真
+		if($2 == "author") {
+
 			# カンマを削除
-			gsub( "," , "" )
+			gsub("," , "")
 
 			# "西暦-ダブルクォート"の部分を削除
-			gsub( /[0-9][0-9][0-9][0-9]-/ , "" )
+			gsub(/[0-9][0-9][0-9][0-9]-/ , "")
 			
 			# "西暦-西暦ダブルクォート"の部分を削除
-			gsub( /[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]/ , "" )
+			gsub(/[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]/ , "")
 
 			# "末尾が西暦とダブルクォート"の部分を削除
-			gsub( /[0-9][0-9][0-9][0-9]\"$/ , "" )
+			gsub(/[0-9][0-9][0-9][0-9]\"$/ , "")
 			
 		}
 		
-		# 4フィールド目を出力
 		print $4
 
-	}' |
+	}
+	' |
 
 	# 区切り文字をカンマに指定,列を行に置換
 	paste -s -d ',' - |
@@ -94,7 +95,7 @@ if [ -p /dev/stdin ] ; then
 	isbn=$(cat - )
 
 	# apiを叩く
-	"hit_api" |
+	parser |
 
 	tee -a "${file}"
 
@@ -122,7 +123,7 @@ elif [ "${isbn}" = "not_input" ] ; then
 		echo ""
 	
 		# apiを叩く
-		"hit_api" |
+		parser |
 
 		# 指定ファイルに追記,指定されてない場合は/dev/nullへ
 		tee -a "${file}"
